FROM node:18 AS build

WORKDIR /app
COPY . .
RUN npm install
RUN npm run build --workspace=apps/frontend

FROM nginx:alpine

COPY --from=build /app/apps/frontend/dist /usr/share/nginx/html
COPY infrastructure/docker/nginx.conf /etc/nginx/conf.d/default.conf
